### ISSUE TITLE
Ревью по проекту

### ISSUE THREAD

**Issue by DramatikMan** [maxgalanov/RecSysYearProject#1]
- [x] В [requirements.txt](https://github.com/maxgalanov/RecSysYearProject/blob/main/hse_rec_sys/requirements.txt) не указаны версии зависимостей. Это нужно для стабильной воспроизводимости вашей логики. В идеале лучше использовать менеджер среды, поддерживающей lock зависимостей по хэшу дистрибутива (например [Poetry](https://python-poetry.org/) или [PDM](https://pdm.fming.dev/latest/))
- [x] Для автоматического форматирования кода по стандартам, соответствующим рекомендациям PEP и общепринятым best practices, могу порекомендовать утилиты [Black](https://black.readthedocs.io/en/stable/) (работает и с Jupyter тетрадками при установке `black[jupyter]`) и [Ruff](https://beta.ruff.rs/docs/)

**Comment by maxgalanov** [comment]
Всё исправлено, просим проверить :)

**Comment by DramatikMan** [comment]
Засчитано
